### ISSUE TITLE
Linux installation without DOCKER

### ISSUE THREAD

**Issue by Physfock** [GQCG/GQCP#1070]
How to install this library in Linux Fedora  without DOCKER?

**Comment by xdvriend** [comment]
If you head to our [documentation page](https://gqcg.github.io/GQCP/landing-page.html) you will find a variety of ways to install and run GQCP, either by using docker, installing GQCP using conda or by building GQCP locally using CMake.

**Comment by Physfock** [comment]
The issue can be attributed to the obsolescence of the CMake instructions. The software requires outdated libraries, some of which are incompatible with each other. Furthermore, the installation process via conda 

conda create --name gqcp 
source activate gqcp (this wrong, it should be conda activate gqcp)
conda install -c gqcg -c intel -c conda-forge gqcp (-c intel gives error 403)

is also unsuccessful, as the Python environment within the conda container is unable to locate the required library. 
While the Docker approach is effective, it is also relatively slow, particularly when utilizing cc-pvtz basis sets, even for relatively straightforward Hartree-Fock calculations. Which linux system can you recommend for sucessful cmake installation?

**Comment by Physfock** [comment]
I got the strange error inside docker container when running with cc-pvtz basis: 

python: /usr/local/miniconda3/include/eigen3/Eigen/src/LU/PartialPivLU_LAPACKE.h:76: static int Eigen::internal::partial_lu_impl<std::complex<double>, StorageOrder, int>::blocked_lu(Eigen::Index, Eigen::Index, Eigen::dcomplex*, Eigen::Index, int*, int&, int) [with int StorageOrder = 0; Eigen::Index = long int; Eigen::dcomplex = std::complex<double>]: Assertion `info >= 0' failed.
Aborted


with a test of  HF calculations. With small basis sets, there are no problems.
