### ISSUE TITLE
Tests fail with Intel compilers

### ISSUE THREAD

**Issue by lelemmen** [GQCG/gqcp#109]
### CMake log

> -- Building gqcp in Release mode
> CMake Warning at /kyukon/home/apps/CO7/haswell-ib/software/CMake/3.10.3-GCCcore-6.4.0/share/cmake-3.10/Modules/FindBoost.cmake:801 (message):
>   New Boost version may have incorrect or missing dependencies and imported
>   targets
> Call Stack (most recent call first):
>   /kyukon/home/apps/CO7/haswell-ib/software/CMake/3.10.3-GCCcore-6.4.0/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
>   /kyukon/home/apps/CO7/haswell-ib/software/CMake/3.10.3-GCCcore-6.4.0/share/cmake-3.10/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
>   cmake/FindPackages.cmake:5 (find_package)
>   CMakeLists.txt:37 (include)
> 
> 
> -- Boost version: 1.66.0
> -- Found the following Boost libraries:
> --   program_options
> -- cpputil version: 1.5.1
> -- numopt version: 1.5.1
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /user/home/gent/vsc416/vsc41680/GQCG/gqcp/build

### CTest log:
> The following tests FAILED:
> 	  3 - CISolver_FCI_Davidson_test (Failed)
> 	  4 - CISolver_FCI_Dense_test (Failed)
> 	 10 - OO_AP1roG_test (Failed)
> 	 11 - AP1roGPSESolver_test (Failed)
> 	 19 - HamiltonianParameters_test (Failed)
> 	 27 - DIISRHFSCFSolver_test (Failed)
> 	 28 - PlainRHFSCFSolver_test (Failed)
> 	 37 - OO_DOCI_test (Failed)
> 	 38 - RMP2_test (Failed)

**Comment by lelemmen** [comment]
### RMP2 test output


```
Running 2 test cases...
Will read basis set from /apps/gent/CO7/haswell-ib/software/Libint/2.4.2-intel-2018a/share/libint/2.4.2/basis/sto-3g.g94
unknown location(0): fatal error: in "crawdad_sto3g_water": std::runtime_error: The RHF SCF procedure is converged but the MO Fock matrix is not diagonal.
/user/home/gent/vsc416/vsc41680/GQCG/gqcp/tests/RMP2_test.cpp(30): last checkpoint: "crawdad_sto3g_water" test entry
Will read basis set from /apps/gent/CO7/haswell-ib/software/Libint/2.4.2-intel-2018a/share/libint/2.4.2/basis/sto-3g.g94
unknown location(0): fatal error: in "crawdad_sto3g_methane": std::runtime_error: The RHF SCF procedure is converged but the MO Fock matrix is not diagonal.
/user/home/gent/vsc416/vsc41680/GQCG/gqcp/tests/RMP2_test.cpp(53): last checkpoint: "crawdad_sto3g_methane" test entry

*** 2 failures are detected in the test module "RMP2"
```

**Comment by lelemmen** [comment]
During compilation, I'm also getting the following error, maybe it's related:

> [ 70%] Building CXX object src/CMakeFiles/gqcp.dir/RHF/RHFSCFSolver.cpp.o
> /apps/gent/CO7/sandybridge/software/Eigen/3.3.4/include/Eigen/src/Cholesky/LLT.h(329): (col. 3) warning #13212: Reference to ebx in function requiring stack alignment

**Comment by guacke** [comment]
I am currently rewriting the CMake files to check for linker errors.

**Comment by guacke** [comment]
These commits fix the FCI_Davidson_test and FCI_Dense_test, if the -DUSE_MKL=ON flag is passed to numopt and gqcp (if MKL is used for any of the libraries, all derived drivers/test have to be linked to MKL).

**Comment by lelemmen** [comment]
@guacke Could you update the instructions at [gqcpmeta](https://github.com/GQCG/gqcpmeta/tree/master/ugent_cluster) accordingly (i.e. with the `VSC_DATA` part)?

**Comment by guacke** [comment]
@lelemmen I have update gqcpmeta with those instructions.
