### ISSUE TITLE
Add logging options

### ISSUE THREAD

**Issue by lelemmen** [GQCG/GQCP#110]
See [boost.log](https://www.boost.org/doc/libs/1_68_0/libs/log/doc/html/index.html)

**Comment by tmhuysen** [comment]
Redirect libint terminal output to boost logs.

**Comment by lelemmen** [comment]
Add the git SHA too.

**Comment by tmhuysen** [comment]
I will start with an initial results oriented log for the reproduction of my thesis results.

**Comment by tmhuysen** [comment]
Discuss levels.
Backend possibilities:
-HDF5
-JSON

**Comment by lelemmen** [comment]
I'm closing this issue because it is very old. It dates back from the time we didn't have Python bindings.
