### ISSUE TITLE
Use OpenMP for DOCI matvec

### ISSUE THREAD

**Issue by lelemmen** [GQCG/GQCP#129]
Parallelize the matvec and matrix routines.

**Comment by lelemmen** [comment]
@tmhuysen Is this still needed after the usage of `SparseMatrix`?

**Comment by tmhuysen** [comment]
So the SparseMatrix multiplication method can only be used for "spin resolved" FCI methods under the condition that the amount of alpha and beta electrons are similar. DOCI cannot benefit from this at all.
