### ISSUE TITLE
Shared libraries for gqcp?

### ISSUE THREAD

**Issue by lelemmen** [GQCG/gqcp#153]
Is there a possibility to build several dynamic libraries for the gqcp?

**Comment by guacke** [comment]
As the move to the shared library will be a concerted effort among the libraries, I will report here when all feature/shared_library are ready to be merged to develop.

**Comment by lelemmen** [comment]
After resetting the caches, we can compile the dynamic library on Travis again, after the cpputil-numopt-gqcp merger (#184).
