### ISSUE TITLE
Libint data path and libint hpp interface.

### ISSUE THREAD

**Issue by guacke** [GQCG/gqcp#175]
The dependency on the libint data path is unfortunate. We could adjust (i.e. implement our own) BasisSet object by changing the following lines in the standard (Libint) BasisSet object:

```
        // read in ALL basis set components
        for(const auto& basis_component_name: basis_component_names) {
          auto file_dot_g94 = basis_lib_path + "/" + basis_component_name + ".g94";

          // use same cartesian_d convention for all components!
          component_basis_sets.emplace_back(read_g94_basis_library(file_dot_g94, force_cartesian_d));
        }
```

and enforce that users always pass a .g94 basis file.

**Comment by lelemmen** [comment]
This is related to #83.

**Comment by guacke** [comment]
On the HPC infrastructure, the sto-3g basis set is not included in the Libint installation. As such, all checks that rely on this basis set fail.

**Comment by lelemmen** [comment]
Closing this PR in favor of #83.
