### ISSUE TITLE
Redundant matvec calls

### ISSUE THREAD

**Issue by lelemmen** [GQCG/gqcp#191]
In an issue opened in numopt, @tmhuysen said:
> https://github.com/GQCG/numopt/blob/3a0345f4ba70bcf0d5dba35917dcbed8cd9a89aa/src/DavidsonSolver.cpp#L107
> 
> https://github.com/GQCG/numopt/blob/3a0345f4ba70bcf0d5dba35917dcbed8cd9a89aa/src/DavidsonSolver.cpp#L199
> Possibility for:
> replacing multiple matvecs in for loops with sinlge a matvec on multiple vectors at once (matrix of few column vectors)

@lelemmen answered:

> Thanks to Eigen's templatization, this wouldn't require an API change + just a small change in the `HamiltonianBuilder`.

**Comment by tmhuysen** [comment]
This is implemented in #244
