### ISSUE TITLE
Mergeable base class for optimization classes

### ISSUE THREAD

**Issue by tmhuysen** [GQCG/GQCP#196]
`BaseMinimizer` and `BaseSystemOfEquationSolver` have the same private variables and API and can be unified in one base class.
https://github.com/GQCG/gqcp/blob/b51628a3e9e758c8808af8525e835fafccd50290/include/optimization/BaseMinimizer.hpp#L33

https://github.com/GQCG/gqcp/blob/b51628a3e9e758c8808af8525e835fafccd50290/include/optimization/BaseSystemOfEquationsSolver.hpp#L33

**Comment by lelemmen** [comment]
This is no longer needed using the new framework of iterative algorithms that was implemented in #477.
