### ISSUE TITLE
hubbard executable: reading in the upper triangle

### ISSUE THREAD

**Issue by nbilliet** [GQCG/gqcp#208]
The hopping upper triangle is not read correctly from the terminal

Error

> [vsc@gligar05 bin]$ ./hubbard -m "1.0,1.0,1.0" -x 2 -a 1 -b 1 -K 2
> terminate called after throwing an instance of 'std::invalid_argument'
>   what():  The given hopping matrix must be square. Did you maybe pass an upper triangle instead of a full hopping matrix?
> Aborted

**Comment by lelemmen** [comment]
As discussed in Slack, this issue is caused because the Hubbard driver wasn't updated after the implementation of Hubbard classes.

**Comment by lelemmen** [comment]
This was implemented in #210.
