### ISSUE TITLE
bad_alloc error for larger Hubbard systems (9 and 10 sites)

### ISSUE THREAD

**Issue by nbilliet** [GQCG/gqcp#213]
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
/var/spool/pbs/mom_priv/jobs/2128269.master19.golett.gent.vsc.SC: line 20: 27975 Aborted                 ./hubbard -m $line -a 5 -b 5 -K 10 >> test_o.csv

**Comment by tmhuysen** [comment]
Durning the submission of a job could you specify a high amount of memory and see if you run into the same problems?

**Comment by lelemmen** [comment]
Yes, [`std::bad_alloc`](https://en.cppreference.com/w/cpp/memory/new/bad_alloc) is an exception raised when the system isn't able to allocate the required amount of memory.

**Comment by nbilliet** [comment]
Bad alloc still occurs even when submitting the job with "#PBS -l nodes=2:ppn=12:mem=80gb"

**Comment by nbilliet** [comment]
bad allow error still occurs even wehn specifying "#PBS -l nodes=1:ppn=12:mem=64gb" (full ram memory as specified https://www.vscentrum.be/infrastructure/hardware/hardware-ugent for golett)

**Comment by lelemmen** [comment]
Could you try switching to a cluster that has more available RAM? Like phanpy? It might be that Eigen is allocating the Hamiltonian matrix 2x, 3x or even more, in order to gain speed.

**Comment by guacke** [comment]
@nbilliet Could you give a minimal example of the input which causes this behaviour, so that @tmhuysen can start reproducing this error? @tmhuysen Could you profile the application in this case? How much memory should it need in principle to calculate these systems? Why does it need so much more additional memory?

**Comment by nbilliet** [comment]
This is a txt file containing 10 training point for 10 sites sampled [-10,10]
[test_10.txt](https://github.com/GQCG/gqcp/files/2754895/test_10.txt)

**Comment by lelemmen** [comment]
@nbilliet Could you try to test a 9/10-site lattice on Phanpy and check if the error persists?

**Comment by lelemmen** [comment]
The case for 9 lattice sites works.
