### ISSUE TITLE
Travis fails to compile

### ISSUE THREAD

**Issue by lelemmen** [GQCG/gqcp#217]
Apparently, the GCC (4.8.4) linker seems to have trouble linking boost's `program_options` with the executables.

**Comment by tmhuysen** [comment]
https://stackoverflow.com/questions/8652096/link-error-in-boost-program-options-code-on-ubuntu

>"sudo apt-get install libboost-dev" do not install library program_options. I need to install it by "sudo apt-get libboost-program-options-dev"

>"sudo apt-get install libboost-all-dev" will install all boost libraries

>You need to link to the Boost program_options library as not everything in Boost is pure templates

Do we install-all? or install-program-options? Also do we specifically link? Maybe this is something that has changed when installing boost?

**Comment by lelemmen** [comment]
This is fixed in #219.
