### ISSUE TITLE
No error throw 

### ISSUE THREAD

**Issue by tmhuysen** [GQCG/gqcp#225]
https://github.com/GQCG/gqcp/blob/6166c9898d86a9c0dc9cf8303b0b037ea8d848af/src/FockSpace/FockSpace.cpp#L127

Line should be:
`boost::numeric::converter<size_t, double>::convert(dim_double)`

currently returns 0 when overflow, instead of raising an error.

**Comment by lelemmen** [comment]
@tmhuysen Could you fix this issue in a separate hotfix branch? We've discussed that #226 will be inactive.
