### ISSUE TITLE
Separate tests based on importance for shorter compilation times

### ISSUE THREAD

**Issue by tmhuysen** [GQCG/gqcp#259]
We could separate tests into different brackets based importance, in order to reduce compilation times.

**Comment by lelemmen** [comment]
Suggestion: maybe create 5(?) or so test executables, each testing a major part of the library. In this way, the compilation time of all the tests is decreased.

**Comment by guacke** [comment]
The use of precompiled headers has drastically reduced the required time to perform all tests. @lelemmen @tmhuysen Is PR #276 enough to close this issue?

**Comment by lelemmen** [comment]
This issue is resolved in #276.
