### ISSUE TITLE
Cluster compiler warning templated matrix and tensors

### ISSUE THREAD

**Issue by tmhuysen** [GQCG/gqcp#284]
>warning #3466: inheriting constructors must be inherited from a direct base class
      using Eigen::Tensor<Scalar, Rank>::Tensor;  // inherit base constructors
>warning #3466: inheriting constructors must be inherited from a direct base class
      using Eigen::Matrix<Scalar, Rows, Cols>::Matrix;  // inherit base constructors

Known warning, does not appear to have adverse effects.

**Comment by lelemmen** [comment]
This is being resolved in #303.
