### ISSUE TITLE
Failing cluster compilation test: Eigen and MKL

### ISSUE THREAD

**Issue by guacke** [GQCG/gqcp#290]
All calculations that need an SCF type calculation are failing on the cluster (e.g. OO_DOCI_test):
std::runtime_error: RHFSCFSolver::solve(): The RHF SCF procedure is converged but the MO Fock matrix is not diagonal. 

@tmhuysen  Could this be related to the following bug report: 'With MKL enabled, however, the result for the row-major matrix is the transpose of the correct result.' ?http://eigen.tuxfamily.org/bz/show_bug.cgi?id=1476

**Comment by lelemmen** [comment]
This is related to the MKL on the cluster. This should be resolved now.
