### ISSUE TITLE
Additional hierarchy layer in headers

### ISSUE THREAD

**Issue by guacke** [GQCG/gqcp#292]
Should we move the headers inside a 'gqcp' directory? If we do this, then our include statements become:

```
#include "gqcp/Basis/ShellSet.hpp"
```
This would reduce the pollution of the install include directory (i.e. /usr/local/include/version.hpp vs /usr/local/include/gqcp/version.hpp) and is more in line with imports from e.g. Eigen and Boost.

**Comment by lelemmen** [comment]
The user should use `#include <gqcp.hpp>`: `gqcp.hpp` should be installed in the CMake prefix.

The other headers should be installed inside `cmake_prefix/include/gqcp/`.

**Comment by lelemmen** [comment]
See also the discussion in PR #372.
