### ISSUE TITLE
Victini and Skitty clusters (SkyLake architecture) test errors: ProductFockSpace_test

### ISSUE THREAD

**Issue by guacke** [GQCG/gqcp#293]
On the victini cluster, there is currently one failure in ProductFockSpace_test: 

```
/tmp/vsc40558/gqcp/0.1.0/intel-2018a/gqcp/tests/FockSpace/ProductFockSpace_test.cpp(98): error: in "FockSpace_EvaluateOperator_Dense_diagonal_false": check two_electron_evaluation1.isApprox(two_electron_evaluation2) has failed
```

Please use the EasyBuild procedure to reproduce this error.

**Comment by guacke** [comment]
Note that this error does not occur on delcatty, nor golett.

**Comment by tmhuysen** [comment]
The default tolerance for the comparison is 1.0e-12. Try 1.0e-10.

**Comment by guacke** [comment]
Answer HPC:

We have run into issues like this before on the Skylake systems, usually involving tests that fail because of slightly diverging floating point values.

We can usually mitigate the issues by compiling at a slightly lower performance level (e.g. -O1 rather than -O2, by enabling the 'lowopt' toolchain option in EasyBuild), or by disabling architecture-specific optimizations (i.e. tell EasyBuild not to use -xHost or -march=native by setting the 'optarch' toolchain option to False).

See for example the discussion in https://github.com/easybuilders/easybuild-easyconfigs/pull/4199 and the follow-up in https://github.com/easybuilders/easybuild-easyconfigs/pull/7115 .

It's also possible that updating to a newer toolchain could help; you may be hitting a compiler bug with intel/2018a on Skylake, I think intel/2018b has significantly better support for Skylake/AVX512 systems...

**Comment by guacke** [comment]
As the performance impact of losing O2 is rather large, I am first going to try switching to a newer toolchain.
