### ISSUE TITLE
Improve consistency of include guards

### ISSUE THREAD

**Issue by lelemmen** [GQCG/gqcp#296]
Right now, there are two syntaxes we use for the include guards. We have `Filename_h` (because of Xcode) and `GQCP_FILENAME_HPP`. My preference goes to `GQCP_FILENAME_HPP`. 

In order to fix this issue, we might even write a python script that does it for us (like the copyright header script.)

**Comment by guacke** [comment]
I would rather replace all header guards by #pragma once:
https://stackoverflow.com/questions/1143936/pragma-once-vs-include-guards

**Comment by lelemmen** [comment]
I've voted for `#pragma once`. What about @tmhuysen?
