### ISSUE TITLE
Vector as member instead of deriving from vector.

### ISSUE THREAD

**Issue by guacke** [GQCG/gqcp#302]
As caught by the Intel compilers, the std::vector was not meant to be derived from: 
https://stackoverflow.com/questions/4513696/inheriting-vectors-and-initialization

As such, for instance, ShellSet should have a vector as a member instead of deriving from a member.

**Comment by lelemmen** [comment]
I agree. This also closes #263.

Could you put the Intel compiler warning in this issue for later reference?

**Comment by lelemmen** [comment]
This was fixed in #353.
