### ISSUE TITLE
Additional namespaces?

### ISSUE THREAD

**Issue by guacke** [GQCG/gqcp#304]
Should we add additional namespaces in gqcp? E.g. change:
```
GQCP::AOBasis
```
to
```
GQCP::Basis::AOBasis
```

**Comment by lelemmen** [comment]
I would rather put everything inside the `GQCP` namespace, I feel names are getting too long otherwise. For example, we would then have: `GQCP::OrbitalOptimization::Localization::ERJacobiLocalizer`, which is a bit much, even for me.

**Comment by guacke** [comment]
Agreed. Closing issue.

**Comment by guacke** [comment]
https://stackoverflow.com/questions/2564135/should-every-class-have-its-own-namespace
