### ISSUE TITLE
Object-oriented refactor

### ISSUE THREAD

**Issue by lelemmen** [GQCG/GQCP#330]
Embracing a more object-oriented programming style (even though we were already doing a pretty good job for it) would mean:
- that all current classes should be scrutinized to make sure they expose **what they behave like** instead of their internals: this means that every objects defines an interface;
- this would consequently mean that we should remove all `get_` methods, because they expose internals. A simple renaming of `get_K()` to `numberOfSpatialOrbitals()` suffices, I think;
- There should be a distinction between a concept (i.e. a class) and its representation. For example, I have previously implemented `AP1roGGeminalCoefficients` that behave like mathematical derivations: `G(j,b)` corresponds to `G_j^b`. I should think more about the internal representation: a Matrix, a special type of matrix that is suited for occupied-virtual entities, or a vector, but changing the internals shouldn't change `AP1roGGeminalCoefficients` itself.

**Comment by lelemmen** [comment]
Should we move `ChemicalMatrix`, `ChemicalRankFourTensor`, `Matrix`, `Tensor`, `SquareMatrix` and `SquareRankFourTensor` inside a folder `Mathematical/Representation`?

**Comment by lelemmen** [comment]
Embracing a more object-oriented programming style (even though we were already doing a pretty good job for it) would mean:
- [ ] that all current classes should be scrutinized to make sure they expose _what they behave like_ instead of their internals
- [ ] this would consequently mean that we should remove all `get_` methods, because they expose internals. A simple renaming of `get_K()` to `numberOfSpatialOrbitals()` suffices, I think
- [ ] There should be a distinction between a concept (i.e. a class) and its representation. For example, I have previously implemented `AP1roGGeminalCoefficients` that behave like mathematical derivations: `G(j,b)` corresponds to `G_j^b`. I should think more about the internal representation: a Matrix, a special type of matrix that is suited for occupied-virtual entities, or a vector, but changing the internals shouldn't change `AP1roGGeminalCoefficients` itself.

**Comment by tmhuysen** [comment]
That's fine by me, however I would like it if there was some resemblance in the methods as to wether the returned value is a member of class or not (so that const& is required) versus a new entity.

**Comment by lelemmen** [comment]
> That's fine by me, however I would like it if there was some resemblance in the methods as to whether the returned value is a member of class or not (so that const& is required) versus a new entity.

Yes, of course: we're keeping `const&`, for sure. Even though these methods do actually expose object internals (in a read-only fashion), the interface is still clean and a user/other develop doesn't have to know the internal name of a member to be able to access it.
