### ISSUE TITLE
Test Python Bindings

### ISSUE THREAD

**Issue by guacke** [GQCG/gqcp#335]
All Python bindings should be tested to make sure that no conversion errors have occurred and that all bindings furnish correct results.

**Comment by lelemmen** [comment]
@guacke Isn't that a lot of duplicate work? I think if the Python bindings compile, then all types have been properly converted. Since the C++ library is fully-tested, I'm not sure what the added benefit is of testing the Python bindings, unless you can convince me with a use case of course.

**Comment by guacke** [comment]
The Python bindings should be indeed be checked on a per use case basis. As such, we should double check that e.g. the FCI and Hubbard drivers furnish the exact same results as 'pure C++' gqcp invocations. This should check that no interfacing errors have occurred (double -> float, matrix transpositions...).

**Comment by lelemmen** [comment]
Ok, I agree. As you've mentioned 'per use case basis', I don't think it would be that much work to do some small tests instead of fully translating the C++ tests to Python as I was initially thinking.
