### ISSUE TITLE
Conda installer for Spectra.

### ISSUE THREAD

**Issue by lelemmen** [GQCG/gqcp#338]
Since the installation of dependencies is very easy using conda, does it still make sense to keep Spectra as a git submodule?

**Comment by guacke** [comment]
I would also prefer a conda Spectra installer. Note that this implies that we have to write a conda installer and an EasyBuild script. @tmhuysen What would you prefer?

**Comment by guacke** [comment]
I have begon work on 

- [ ] Implementing a CMakeLists.txt for Spectra
- [ ] Making a Conda build script
- [ ] Building for OSX and Linux
- [ ] Pushing those builds to our repo at Anaconda

You can follow my progress on GQCG/Spectra.
