### ISSUE TITLE
Refactor Python Bindings

### ISSUE THREAD

**Issue by guacke** [GQCG/gqcp#340]
As suggested by @lelemmen:

It seems that a lot of things are happening inside the constructor of the HubbardDriver. In my opinion, it would be better to only use the constructor to construct the valid context of the object, and then use a method like solve() or so to do the actual calculations and ‘set’ the energies/DMs that the user would like to use.

I’ve added some comments and suggestions.

As far as the structuring of the Python binding goes, what do you think of the following idea? We could include a folder gqcpy (or pygqcp, I think we should still vote on that because both of them are fine for me) and then structure the python bindings as in the C++ source code itself. For the current Hubbard driver, this would then mean to create the Python module in : root/pygqcp/Drivers/.

**Comment by guacke** [comment]
As suggested by @lelemmen:

I think it would be useful if the previous lines of code that produces a HoppingMatrix from a std::string was actually made into a named constructor inside the HoppingMatrix class.

**Comment by guacke** [comment]
As suggested by @lelemmen:

Since only a solve method would use the ProductFockSpace, Hubbard Hamiltonian builder and CISolver, I don’t think it is necessary to include these as members of the class (they don’t need to exist outside of the actual calculation part).

Removing these objects as members from HubbardDriver would bypass the issue that you tried to solve by using shared_ptrs.

**Comment by guacke** [comment]
As suggested by @lelemmen:

In the solve method, you could calculate and ‘store’ the targeted energies and then just return them here.

**Comment by lelemmen** [comment]
These changes were incorporated into #341, which was merged into #315.
