### ISSUE TITLE
Rename FockSpace to ONVBasis

### ISSUE THREAD

**Issue by tmhuysen** [GQCG/GQCP#345]
It could be more conceptually flexible to introduce (derivations) of ONVBasis's instead of FockSpaces.

**Comment by lelemmen** [comment]
This would indeed be a nice conceptual change.

**Comment by tmhuysen** [comment]
Is this going to be strictly a rename? Or are we going to associate other changes with the rename?
There is some nuance for the re-naming of `FockSpace` as this is used as both the full spin orbital ONVBasis and the doubly occupied ONVBasis.

**Comment by tmhuysen** [comment]
For evaluations however they are distinctly different so with the rename, a doubly occupied evaluation should be added, since this is only present in the `DOCI` class

**Comment by lelemmen** [comment]
@tmhuysen It might be indeed interesting to think about these bases. I. e. we should spend some time on preparing the code to work with general spin orbitals (in the `ONVBasis`), 'product' spin orbitals (in a `ProductONVBasis`?) and doubly-occupied ONV bases.

**Comment by tmhuysen** [comment]
In light of the CI refactor I feel like we should apply this the rename plans for Fock spaces to various specialized ONVBases, potentially starting from two bases one for spinor and one for a resolved frame work? Then specialize for doubly-occupied ONV basis for example.  The only CI-Solver left to cover is Hubbard, which is essentially a one-electron evaluation in a resolved full ONV basis with a custom diagonal.

**Comment by lelemmen** [comment]
@tmhuysen I'm interested to see/hear your thoughts!

Regarding the Hubbard and DOCI cases, perhaps there is some some significance in them being 'model Hamiltonians'?
