### ISSUE TITLE
Git SHA1 and version info when loading Python?

### ISSUE THREAD

**Issue by lelemmen** [GQCG/gqcp#346]
When doing `import gqcpy`, it would be nice to access the git SHA1 and the version info of the commit the library was compiled on.

We could just expose the version info to Python, or we could even force a [print message](https://stackoverflow.com/questions/40930772/python-creating-a-module-that-prints-something-when-imported) that is shown during the `import gqcpy` call. We can even opt for both of them.

**Comment by guacke** [comment]
Agreed. As a minor comment, could we also decide on a version system (e.g. GQCP v0.1.3)? This is easier from a user perspective, as we can then state something along the lines of 'Python bindings are supported as of version x.x.x'.

**Comment by lelemmen** [comment]
Yes, any versioning system is fine for me, as long as we currently stay within v0.x.x. We're making far too many API changes for the major version number to be relevant.
