### ISSUE TITLE
Wavefunction Fock space templates

### ISSUE THREAD

**Issue by tmhuysen** [GQCG/GQCP#363]
Consider looking into the possibility of adding the underlying Fock space or ONV expansion as a template to the `GQCP::WaveFunction` class

**Comment by tmhuysen** [comment]
Issue #345 should be dealt with before this should be implemented

**Comment by lelemmen** [comment]
We should keep this in mind when doing the low-level CI refactor (#505).

**Comment by lelemmen** [comment]
I’m very much in favor of this change, since this fits in the frame of thought of everything making ‘compile-time sense’: only for `LinearExpansion`s whose underlying basis spans the whole Fock space, the method `basisTransform` makes sense.
