### ISSUE TITLE
GQCPY Hubbard interface broken.

### ISSUE THREAD

**Issue by guacke** [GQCG/gqcp#373]
When running this script

`import gqcpy; hubbard = gqcpy.Hubbard("1.0, 2.0, 1.0", 1, 2, 2); hubbard.solve(); hubbard.get_energies()`

I get the following erroneous result: `[2.0]`. This bug also implies that resolving issue #335 should be high priority.

**Comment by tmhuysen** [comment]
What is incorrect about the result? U = 1, there are 4 electrons in two sites. Meaning only 1 ONV in the space. There are no "hoppings", only two doubly occupied sites = 2*U = 2.

**Comment by guacke** [comment]
@tmhuysen Correct! I used to reference myself on the following command:

`import gqcpy; hubbard = gqcpy.Hubbard("1.0, 2.0, 1.0", 1, 1, 1); hubbard.solve(); hubbard.get_energies()`

which only has two electrons.
