### ISSUE TITLE
CPHF for currents

### ISSUE THREAD

**Issue by lelemmen** [GQCG/GQCP#376]
There are two of CP(R)HF equations that have to be solved when calculating response current densities (magnetic inducibilities #498).

- [x] In both cases the 'response force constant' is equal: it is the 'orbital hessian for a purely imaginary response'. In #600, we had implemented a prototype for this Hessian:

https://github.com/GQCG/GQCP/blob/1e6bcb6a28f2c0e1323484b69d64c193dcfd9f34/gqcp/include/QCModel/HF/RHF.hpp#L195-L240

We require the 'response force', i.e. the (negative of) the right-hand side of the linear response equations, for two types of perturbation:
- [x] The perturbation due to the magnetic field;
https://github.com/GQCG/GQCP/blob/1e6bcb6a28f2c0e1323484b69d64c193dcfd9f34/gqcp/tests/Processing/Properties/properties_test.cpp#L249-L265
- [x] The perturbation due to the gauge origin translation;
https://github.com/GQCG/GQCP/blob/1e6bcb6a28f2c0e1323484b69d64c193dcfd9f34/gqcp/tests/Processing/Properties/properties_test.cpp#L274-L299

**Comment by lelemmen** [comment]
@xdvriend I'm wondering if the code snipped I added to the PR body rings a bell. Is it related to (a linear combination of) some of the RHF external stability matrices?

**Comment by xdvriend** [comment]
That was an impressive suspicion you had there! 

![IMG_0027](https://user-images.githubusercontent.com/54795591/101898524-911de000-3bac-11eb-995e-45b0e41e9459.jpg)
