### ISSUE TITLE
Python bindings for eigenvectors and 2-RDMs Hubbard 

### ISSUE THREAD

**Issue by nbilliet** [GQCG/GQCP#407]
**Describe the feature you'd like**
Add the ability to return the eigenvectors and the 2-RDMs for the Hubbard class of  the gqcpy module

**Describe what the current code offers in relation to what it lacks**
Currently the only retrievable information consists of the energies and the 1-RDMs of any Hubbard molecule

**Additional context**
The features described above would be in line with the research concerning machine learning applied to the Hubbard model

**Comment by lelemmen** [comment]
@nbilliet Could you use the "feature issue" template instead of just the current one-liner? 

I also think it would be a nice opportunity for you to get more acquainted with the code if you implemented this feature yourself.

**Comment by lelemmen** [comment]
@nbilliet I'm closing this issue because we have discussed that updating a 'driver' isn't the way to use gqcpy.
