### ISSUE TITLE
Code review 18/10/2019

### ISSUE THREAD

**Issue by lelemmen** [GQCG/GQCP#442]
**Suggested topics and issues**
We haven't had a code review for the longest time! I think it's time to set up a plan on how we are going to handle further developments to the code during the upcoming year. I especially think it will be necessary to define some clear goals what we want to accomplish with the code this year.

Some things that we could do:
- check the current list of issues and set internal priorities
- define milestones and soft deadlines

**Invited developers**
18/10/2019 during the outline meetings
@tmhuysen @guacke

**Comment by guacke** [comment]
@lelemmen Ok!

**Comment by tmhuysen** [comment]
@lelemmen Ok!

**Comment by tmhuysen** [comment]
I have try-out practical at 9:00 in the morning (however this will likely not take long), and the practicum itself at 13:00

**Comment by tmhuysen** [comment]
The practical and try-out has been moved.
