### ISSUE TITLE
PlainRHFSCFSolver / RHF

### ISSUE THREAD

**Issue by tmhuysen** [GQCG/GQCP#450]
**Describe the bug**
Non-converged `PlainRHFSCFSolver` is able to return a solution, resulting in an error:
>malloc: *** error for object 0x7fe5806020f8: pointer being freed was not allocated

**To Reproduce**
Solve RHF with `PlainRHFSCFSolver` for molecule NO+ with intramolecular distance of 2 bohr, then call `PlainRHFSCFSolver::get_solution();`

**Expected behavior**
An error should either be thrown after it failed to converge, or an error should be thrown when requesting solution from non-solved solver wrapper.

**Screenshots and logs**
>malloc: *** error for object 0x7fe5806020f8: pointer being freed was not allocated

**Operating system**
 - OS: macOS 
 - Version 10.14.6

**Comment by tmhuysen** [comment]
This malloc likely stems from -O3 compiler optimization skipping throws.

**Comment by lelemmen** [comment]
@tmhuysen Could you confirm that this bug is squashed after #477?

**Comment by tmhuysen** [comment]
Ah, this was due to the -O3 flag skipping error throws
