### ISSUE TITLE
Encapsulate Mulliken partitioning API

### ISSUE THREAD

**Issue by tmhuysen** [GQCG/GQCP#452]
**Describe the current state of a part of the code**
The current API for using Mulliken's partitioning is using a raw vector `ao_list`.

**Describe a change that would improve the code base**
- [x] We can introduce a class

```cpp
class MullikenPartitioning {
private:
    // A set of AO indices that are included in the Mulliken-partitioning of an AO basis.
    std::vector<size_t> m_indices;

public:
    const std::vector<size_t>& indices() const;

    SquareMatrix<double> partitionMatrix() const;  // Return the partition matrix P_A

    RTransformationMatrix<double> projectionMatrix() const;  // Return the projection matrix C^-1 P_A C
};
```

- [x] Instances of this class may be generated through the addition of the following API on `RSpinOrbitalBasis`:
```cpp
MullikenPartition mullikenPartition(selector) const;
```

where `selector` is a user-supplied function that returns `true` if a shell as its argument should be included in the partitioning or not.

- [x] Finally, we can use the `MullikenPartition` instance by combining it with an `RSQOneElectronOperator`:
```cpp
RSQOneElectronOperator partitioned(MullikenPartition) const;
```

- [x] Effectively implementing the calculation of the [Mulliken-partitioned operator's matrix elements](https://gqcg-res.github.io/knowdes/mulliken-partitioning.html) can be done through a one-index transformation, as discussed in [spinor connections, which are used in perturbation-dependent Fock spaces](https://gqcg-res.github.io/knowdes/perturbation-dependent-fock-spaces.html).

- [x] Add 'selector' tests.
- [x] Improve Mulliken population tests.

**Comment by tmhuysen** [comment]
I'm not 100% onboard to create a wrapper class for ao_list, its meaning is in its name, but maybe allow Spinor basis to create the instance.

**Comment by lelemmen** [comment]
> I'm not 100% onboard to create a wrapper class for ao_list, its meaning is in its name, but maybe allow Spinor basis to create the instance.

I agree that a SpinorBasis should be able to create the raw vector/wrapper object.

**Comment by lelemmen** [comment]
The theory (for 1-electron operators) is clear, I've updated the description of this PR to reflect the most current progress.

**Comment by lelemmen** [comment]
We can introduce a class

```cpp
class MullikenPartitioning {
private:
    // A set of AO indices that are included in the Mulliken-partitioning of an AO basis.
    std::vector<size_t> m_indices;

public:
    const std::vector<size_t>& indices() const;

    SquareMatrix<double> partitionMatrix() const;  // Return the partition matrix P_A

    RTransformationMatrix<double> projectionMatrix() const;  // Return the projection matrix C^-1 P_A C
};
```

Instances of this class may be generated through the addition of the following API on `RSpinOrbitalBasis`:
```cpp
MullikenPartition mullikenPartition(selector) const;
```

where `selector` is a user-supplied function that returns `true` if a shell as its argument should be included in the partitioning or not.

Finally, we can use the `MullikenPartition` instance by combining it with an `RSQOneElectronOperator`:
```cpp
RSQOneElectronOperator partitioned(MullikenPartition) const;
```

Effectively implementing the calculation of the [Mulliken-partitioned operator's matrix elements](https://gqcg-res.github.io/knowdes/mulliken-partitioning.html) can be done through a one-index transformation, as discussed in [spinor connections, which are used in perturbation-dependent Fock spaces](https://gqcg-res.github.io/knowdes/perturbation-dependent-fock-spaces.html).
