### ISSUE TITLE
Unrestricted spinor basis

### ISSUE THREAD

**Issue by tmhuysen** [GQCG/gqcp#453]
**Describe the feature you'd like**
A spinor basis specialized for unrestricted calculations

**Describe what the current code offers in relation to what it lacks**
Currently the code uses two spinor bases, one for alpha and beta. This allows calculation of the mixed two-electron integrals with different underlying bases, and easier to use spin-targeted transformations.

**Comment by lelemmen** [comment]
> **Describe what the current code offers in relation to what it lacks**
> Currently the code uses two spinor bases, one for alpha and beta. This allows calculation of the mixed two-electron integrals with different underlying bases, and easier to use spin-targeted transformations.

What do you mean with "easier to use spin-targeted transformations"?

**Comment by tmhuysen** [comment]
>What do you mean with "easier to use spin-targeted transformations"?

If you want to transform the beta component, you have to pass the correct SpinorBasis, that of beta, there are two existing bases, this gives room for potential developer/user mistakes.
