### ISSUE TITLE
Add functionality of the mathematical representation of the operators to the SQOperators

### ISSUE THREAD

**Issue by tmhuysen** [GQCG/GQCP#454]
**Describe the current state of a part of the code**
Currently not all `QCTensor` and `QCMatrix` functionality is applicable to operators. A clear example is when performing `matrixContraction` on a `SQTwoElectronOperator`, one has to currently extract & copy the parameters, perform the contraction and replace the operator with fresh instance initialized with the modified parameters.

**Describe a change that would improve the code base**
The idea is to add this functionality to the One- and `TwoElectronSQOperator`s

**Additional context**
Is there a potential to add this functionality without copy declaring all the methods?
related issues: #415

**Comment by lelemmen** [comment]
> **Describe the current state of a part of the code**
> Currently not all `QCTensor` and `QCMatrix` functionality is applicable to operators

Which functionality? Which operators?

> **Describe a change that would improve the code base**
> The idea is to add this functionality

Which functionality?

---

Please update your feature request with more clarification and examples.

**Comment by lelemmen** [comment]
It seems that this issue is also related to #415. Is this what you were looking for?

**Comment by lelemmen** [comment]
Closing due to not being sufficiently clear.
