### ISSUE TITLE
Separate the code into API and implementation

### ISSUE THREAD

**Issue by tmhuysen** [GQCG/GQCP#455]
**Describe the current state of a part of the code**
Currently there are routines such as the evaluation of an `SQOperator` in a `FockSpace` who are gated to only accept `SQOperator` objects, while the effective algorithm extracts raw data objects to perform the routines. These complex routines can thus only be accessed through the creation of these objects.

**Describe a change that would improve the code base**
The idea would be to decouple the effective algorithm from these objects, while retaining the current interfaces. A new implementation would then extract the raw data and call the effective algorithm for the user/new-developer. e.g `FockSpace::EvaluateOperator` would still exist & simply extract the operators and pass them to a different method `FockSpace::EvaluateOperatorRaw`. A direct advantage would be to be able to avoid the (utility) baggage of the classes encompassing this raw data in case of specialized memory heavy routines. Decoupling can also leave the specialized routines completely unaffected by design refactors.

**Comment by lelemmen** [comment]
Closing this issue because at the moment, this is not how the library is designed.
