### ISSUE TITLE
Add an orbital-rotation based initial guess for the Davidson algorithm

### ISSUE THREAD

**Issue by tmhuysen** [GQCG/GQCP#456]
**Describe the feature you'd like**
A guess generator for Davidson based on the magnitude of the orbital rotation Hessian eigenvalues.

**Describe what the current code offers in relation to what it lacks**
The code currently possesses no other guess generator other than random or the Hartree-Fock expansion.

**Additional context**
The magnitude of the orbital rotation Hessian eigenvalues could be an indicator of how important the virtual orbital occupations are in a configuration. The smaller the magnitude the greater the importance (the lower the energy change accompanied). Note that the effectiveness of this proposal is not known.

**Comment by lelemmen** [comment]
This issue is related to #72.

**Comment by lelemmen** [comment]
There is no sound theoretical evidence (no derivation has been done yet), so I'm closing this issue.
