### ISSUE TITLE
Caching for github actions

### ISSUE THREAD

**Issue by tmhuysen** [GQCG/GQCP#463]
**Describe the current state of a part of the code**
Currently github actions is not caching

**Describe a change that would improve the code base**
It would save time in the build if we cache dependencies

**Additional context**
There is a commit "turn on caching" which edits the gqcp.yml file with caching, simply copying this code could suffice as the issue with caching could have been a "transient" one on the server side of the caching actions repo.

**Comment by lelemmen** [comment]
Since we've moved away from GitHub Actions, this issue isn't relevant at the moment.
