### ISSUE TITLE
Wave function analysis

### ISSUE THREAD

**Issue by tmhuysen** [GQCG/GQCP#479]
**Describe the feature you'd like**
I would like to see more tools to analyze a wavefunction, and pair this with conversion to certain outputs. In particular extraction of important coefficient paired with their index in the Fock space and output files readable by GAMESS (US). 

**Describe what the current code offers in relation to what it lacks**
Currently these routines do not exist

**Comment by lelemmen** [comment]
Closed because the issue is not clear enough.
