### ISSUE TITLE
Duplicate code in CI methods?

### ISSUE THREAD

**Issue by lelemmen** [GQCG/gqcp#49]
There seems to be duplicate/extremely similar code in the CI builder methods.

**Comment by lelemmen** [comment]
@tmhuysen Could you update on this issue: what remains to be done?

**Comment by tmhuysen** [comment]
Hubbard has to be updated similarly to that of FCI. For DOCI I do not see an immediate solution (for later) as basic approach to unifying the Matrix and Matvec code puts quite a dent in the performance.
