### ISSUE TITLE
Two electron integrals in generalised spinor basis

### ISSUE THREAD

**Issue by xdvriend** [GQCG/GQCP#512]
@lelemmen 

**Describe the feature you'd like**
A possibility to get the two electron integral tensor in generalised spinor basis.

**Additional context**
This would be a very useful addition, in order to be able to perform Hessian calculations in a generalised basis.

**Comment by lelemmen** [comment]
@xdvriend Thanks for opening this issue. I'll make sure that the Python bindings are also updated accordingly.
