### ISSUE TITLE
Implement a test for the quantization of the Coulomb operator in GSpinorBasis

### ISSUE THREAD

**Issue by lelemmen** [GQCG/GQCP#517]
**Describe the current state of a part of the code**
After #514, we'll have the ability to quantize the Coulomb operator in a general spinor basis. However, I didn't really know (read: spend time) how to actually test if the results are correct.

**Describe a change that would improve the code base**
@xdvriend Could I delegate the implementation of such a test to you?

**Comment by xdvriend** [comment]
I believe This issue can be closed as
`BOOST_AUTO_TEST_CASE(Coulomb_quantization_zero_blocks)`
is already implemented. Is this correct @lelemmen ?

**Comment by lelemmen** [comment]
@xdvriend You're correct.
