### ISSUE TITLE
Generate documentation for the Python bindings

### ISSUE THREAD

**Issue by lelemmen** [GQCG/GQCP#521]
**Describe the feature you'd like**
It would be nice for the users of this library to quickly see which Python bindings have been opened from the C++ library.

**Additional context**
@nbilliet Since the Python bindings are generated with pybind11, we don't really don't want to write this documentation manually. In the [pybind11 documentation](https://pybind11.readthedocs.io/en/stable/advanced/misc.html#generating-documentation-using-sphinx), there is some information on how to generate pybind11-documentation using Sphinx.

I'm also thinking ahead, but would it be hard to export this documentation and make it available on the GQCG GitHub website? @guacke I guess this would require a clean CI/CD.

**Comment by guacke** [comment]
I will look at the required CI/CD steps.

**Comment by guacke** [comment]
Reassigned to docs-developers.

**Comment by lelemmen** [comment]
This issue has been deprecated in favor of #849 and #850.
