### ISSUE TITLE
I cannot install GQCP.

### ISSUE THREAD

**Issue by dariatols** [GQCG/GQCP#524]
**Describe the bug**
When trying to install GQCP, the following error occurs:
git clone -b feature/cmake_refactor https://github.com/GQCG/libcint
Cloning into 'libcint'...
fatal: Remote branch feature/cmake_refactor not found in upstream origin

There is no cmake_refactor branch found in libcint.

**Operating system**
macOS Mojave 10.14.6

**Comment by guacke** [comment]
I will update the documentation and installation procedure.

**Comment by guacke** [comment]
@dariatols Could you try reinstalling GQCP using the new installation instructions, which can be found on branch feature/pybind (or on develop after merge)?

**Comment by dariatols** [comment]
@guacke 

-- Found PythonInterp: /Users/daria/ugent/GQCP/build/$/Users/daria/opt/anaconda3/envs/gqcg_dev/bin/python (found version "1.4")
CMake Error at /Users/daria/opt/anaconda3/envs/gqcg_dev/share/cmake/pybind11/FindPythonLibsNew.cmake:96 (message):
  Python config failure:

Call Stack (most recent call first):
  /Users/daria/opt/anaconda3/envs/gqcg_dev/share/cmake/pybind11/pybind11Tools.cmake:16 (find_package)
  /Users/daria/opt/anaconda3/envs/gqcg_dev/share/cmake/pybind11/pybind11Config.cmake:100 (include)
  CMakeLists.txt:48 (find_package)


-- Configuring incomplete, errors occurred!
See also "/Users/daria/ugent/GQCP/build/CMakeFiles/CMakeOutput.log".

This error happens when I try to run this line of code:
cmake .. -DCMAKE_PREFIX_PATH=$/Users/daria/opt/anaconda3/envs/gqcg_dev -DCMAKE_INSTALL_PREFIX=~/.local -DBUILD_TESTS=TRUE -DBUILD_PYTHON_BINDINGS=TRUE -DPYTHON_EXECUTABLE=$/Users/daria/opt/anaconda3/envs/gqcg_dev/bin/python -DPYTHON_LIBRARY=$/Users/daria/opt/anaconda3/envs/gqcg_dev/lib/libpython3.8.a

**Comment by lelemmen** [comment]
@dariatols I've formatted your comment, just for clarity.

The path that is specified in `PythonInterp` is pretty weird: `/Users/daria/ugent/GQCP/build/$/Users/daria/opt/anaconda3/envs/gqcg_dev/bin/python`.

In a normal installation, I would expect that the path would be `/Users/daria/opt/anaconda3/envs/gqcg_dev/bin/python`, i.e. everything before the dollar sign `$`. Perhaps you have installed the `gqcg_dev` conda environment using a wrong command?

Could you retry installing `gqcg_dev` and see if the problem persists?

**Comment by dariatols** [comment]
@guacke @lelemmen 
I've deleted and reinstalled gqcp_dev using the INSTALL.md and I get the same error message as before.

**Comment by guacke** [comment]
@dariatols Has this issue been resolved?

**Comment by dariatols** [comment]
Yes, thank you!
