### ISSUE TITLE
Several failed tests when installing GQCP

### ISSUE THREAD

**Issue by xdvriend** [GQCG/GQCP#528]
**Describe the bug**
When Trying to install GQCP on my laptop, some test that normally pass, fail. 

**To Reproduce**
I followed the new installation procedure from scratch, in order to install gqcp on my laptop. 
- make works fine
- make test yields 5/90 failed tests.

**Screenshots and logs**
The following tests FAILED:
	 28 - QCRankFourTensor_test (Failed)
	 87 - DOCIRHF_test.py (Failed)
	 88 - FukuiDysonAnalysis_test.py (Failed)
	 89 - MullikenConstrainedFCI_test.py (Failed)
	 90 - OO-DOCI_test.py (Failed)
Errors while running CTest
make: *** [test] Error 8

**Operating system**
 - OS: Catalina 10.15

**Comment by lelemmen** [comment]
For the C++ library related test:
---
Could you `cd` to `GQCP/build/gqcp/tests`, run the `QCRankFourTensor_test` by doing `./QCRankFourTenstor_test` and report the output of the test?


For the Python tests
---
Could you `cd` to `GQCP/build/gqcpy/tests` and run the tests by doing `python TEST_NAME.py` and also report the output of these tests?

**Comment by xdvriend** [comment]
**For the QCRankFourTensor_test:**
Running 5 test cases...
unknown location:0: fatal error: in "QCRankFourTensor_basisTransformInPlace_trivial": signal: SIGSEGV, si_code: 0 (memory access violation at address: 0x00000000)
/Users/Xekke/desktop/thesis/GQCP/gqcp/tests/Mathematical/Representation/QCRankFourTensor_test.cpp:44: last checkpoint: "QCRankFourTensor_basisTransformInPlace_trivial" test entry

*** 1 failure is detected in the test module "QCRankFourTensor"

** For the Python tests:**
When the tests are performed individually, they all pass.
- working directory: GQCP/build/gqcpy/tests
- which python: /Users/Xekke/anaconda3/envs/gqcg_dev/bin/python

**Comment by xdvriend** [comment]
When trying to import GQCPy in an iPython notebook, the following error appeared. Maybe this is related.
![Screenshot 2020-02-19 at 17 38 11](https://user-images.githubusercontent.com/54795591/74853845-c4059780-533e-11ea-93d2-81a705ccff5a.png)

**Comment by guacke** [comment]
@xdvriend For the failing Python tests, could you send me the CMake command you used? 

@xdvriend Please note that the environment.yml has been updated in the feature/pybind branch to incorporate Jupyter notebooks. As such, please install that version of the environment.

**Comment by guacke** [comment]
@xdvriend For the failing QCRankFourTensor_test: which C++ compiler are you using?

**Comment by xdvriend** [comment]
@guacke 
I'll re-install and retry the iPython notebook!
As for the python tests: 
- By just using make test the 5 tests mentioned above fail.
- When running them individually with python DOCIRHF_test.py (e.g.), they pass.

As for the compiler: I thinks it's the default one provided by Apple's Xcode. Can't seem to check it though. Is there a way to verify this?

**Comment by lelemmen** [comment]
> As for the python tests:
> 
> * By just using "make test" as the command, the 5 tests mentioned above fail.
> * When running them individually with "python DOCIRHF_test.py" (e.g.), they pass.

That's already a good sign, so possibly the python executable that is used in `python TEST.py` is still not compatible version-wise with what pybind11 produces.

Could you provide the output for

```bash
which python
python --version
```

and also the command (and output) of the out-of-source build `cmake .. OPTIONS`?

> As for the compiler: I thinks it's the default one provided by Apple's Xcode. Can't seem to check it though. Is there a way to verify this?

This should also be contained in the terminal output you get when doing `cmake .. OPTIONS`.

**Comment by xdvriend** [comment]
The output for the python version:
<img width="433" alt="Screenshot 2020-02-19 at 19 55 52" src="https://user-images.githubusercontent.com/54795591/74867096-5f553780-5354-11ea-83ef-eb52ef070a14.png">
The output of cmake .. OPTIONS:
<img width="1437" alt="Screenshot 2020-02-19 at 20 13 12" src="https://user-images.githubusercontent.com/54795591/74867133-6e3bea00-5354-11ea-967b-2d48ec322d3a.png">

**Comment by lelemmen** [comment]
@xdvriend Thanks for providing the outputs. Could you delete the `build` directory and then retry the installation, and provide the output of that `cmake ..` command? This should hopefully show the C++ compiler.

**Comment by xdvriend** [comment]
This indeed shows the compiler on the first line! I provided the entire output below, in case there might be some other useful information in it.
<img width="1440" alt="Screenshot 2020-02-19 at 21 02 39" src="https://user-images.githubusercontent.com/54795591/74871172-4bf99a80-535b-11ea-9f68-91006050de54.png">

**Comment by lelemmen** [comment]
Indeed, you're compiling with `AppleClang 11.0`. Could you `port install clang-7.0` and try to recompile the library with clang 7.0? (After installing clang 7.0 from MacPorts, CMake should find MacPorts' clang 7.0 instead of AppleClang.)

**Comment by xdvriend** [comment]
After installing Clang-7.0 with macports & trying to recreate the build, with the cmake .. OPTIONS command I get an error I didn't get previously...
Also, he still seems to be using the AppleClang compiler.
<img width="1440" alt="Screenshot 2020-02-19 at 21 27 26" src="https://user-images.githubusercontent.com/54795591/74873041-b3fdb000-535e-11ea-93c9-88aec5bc370b.png">

**Comment by lelemmen** [comment]
@xdvriend Could you try to `export CXX=/opt/local/bin/clang++` in order to let MacPort's clang take precedence?

**Comment by xdvriend** [comment]
Did the export, ran the cmake .. OPTIONS again, and now he can't find any compiler.
<img width="887" alt="Screenshot 2020-02-19 at 21 35 40" src="https://user-images.githubusercontent.com/54795591/74873651-e2c85600-535f-11ea-93a4-5ba8b31e5124.png">

**Comment by lelemmen** [comment]
@xdvriend Where did MacPorts install clang 7?

**Comment by xdvriend** [comment]
/opt/local/bin/port as far as I know. Also tried export CXX=/opt/local/bin/clang-7.0 but this gives the same problem.

**Comment by lelemmen** [comment]
@xdvriend I think you'll have to figure out the exact path to the MacPort's clang 7.0 and then `export` it.

**Comment by xdvriend** [comment]
Found the entire path (I believe) and exported: `export CXX=/opt/local/var/macports/software/clang-7.0`. 
However, now I get an error in the output saying that the C++ compiler can't compile a simple test program. 
<img width="1440" alt="Screenshot 2020-02-19 at 22 02 44" src="https://user-images.githubusercontent.com/54795591/74876066-9717ab80-5363-11ea-8636-e50efffd161f.png">

**Comment by lelemmen** [comment]
@guacke What compiler should users use when compiling GQCP if they have dependencies installed through conda?

**Comment by guacke** [comment]
@xdvriend The above output hints that I will have to reconfigure your Macports and Conda installation. We will revisit this issue once I have done so.

**Comment by xdvriend** [comment]
@guacke Allright, I'll leave it as is for now then. We can discuss this further tomorrow.

**Comment by guacke** [comment]
@xdvriend Is this issue resolved?

**Comment by xdvriend** [comment]
@guacke Since you installed everything on my system, I haven't tried another build myself. However, since I can now use GQCpy, I believe it is resolved.
