### ISSUE TITLE
Unknown exception errors when calculating integrals through Python bindings

### ISSUE THREAD

**Issue by guacke** [GQCG/GQCP#549]
**Describe the bug**
Installation on Google Colab leads to 'unknown exception' errors when calculating integrals through the Python bindings.

**To Reproduce**
```python

import gqcpy
import numpy as np
import matplotlib.pyplot as plt

def gqcp_hydrogen_chain(num_hydrogens, distance):
    nuclei = []
    for index in range(num_hydrogens):
        nuclei.append(gqcpy.Nucleus(1, 0.0, 0.0, index*distance))
    molecule = gqcpy.Molecule(nuclei)
    return molecule

molecule = gqcp_hydrogen_chain(4, 4)
spinor_basis = gqcpy.RSpinorBasis(molecule = molecule, basisset_name="sto-3g")
```

**Proposed solution**
This exception can occur because the Python bindings are currently tested for import; not for functionality. A Python test that checks if integrals can be calculated will allow us to resolve this problem upstream.

**Comment by lelemmen** [comment]
@guacke I think your example is incomplete. Nowhere any integrals are calculated.

**Comment by lelemmen** [comment]
@guacke Is this bug still live?
