### ISSUE TITLE
Unrestricted types

### ISSUE THREAD

**Issue by lelemmen** [GQCG/GQCP#558]
**Describe the feature you'd like**
As a first milestone in order to implement UHF, we should tackle the problem of how to encapsulate objects that are of 'unrestricted' type. 

- [x] This would mean that we should make sure that `USpinorBasis` is linked to `USQOneElectronOperator`,  `USQTwoElectronOperator` and `USQHamiltonian`, following an API that is similar to what `RSpinorBasis` provides.

**Comment by lelemmen** [comment]
@xdvriend I think that it's a good start for you to work on this issue before implementing UHF SCF. This will make sure that you learn to work with the internals of the code first, and afterwards UHF SCF will be quite parallel to RHF SCF.

**Comment by xdvriend** [comment]
I will take this step by step. First, i will try and fix the USQ Operators one by one.

- [ ] USQOneElectronOperator #561 

- [ ] USQTwoElectronOperator

- [ ] USQHamiltonian
