### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by dariatols** [GQCG/GQCP#565]
I get the following error when I want to Clean Refigure All Projects in VSCode. 
```
CMake Error at /usr/local/Cellar/cmake/3.14.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
[cmake]   Could NOT find Int2 (missing: Int2_INCLUDE_DIR Int2_LIBRARY)
[cmake] Call Stack (most recent call first):
[cmake]   /usr/local/Cellar/cmake/3.14.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
[cmake]   cmake/FindInt2.cmake:31 (find_package_handle_standard_args)
[cmake]   CMakeLists.txt:24 (find_package)
```
What am I doing wrong?

**Operating system**
 - OS: macOS
 - Version [e.g. 10.15]

**Comment by lelemmen** [comment]
Which conda environment are you using?

**Comment by dariatols** [comment]
@lelemmen gqcg_dev, the one @guacke told me to install.

**Comment by lelemmen** [comment]
Could you schedule in a meeting with me and @guacke? It's pretty hard to figure out what's going wrong with this little information.

What have you tried to resolve the issue?

**Comment by dariatols** [comment]
I have clang-11.0.3 installed on my system. When I installed clang-7.0, VSCode could not find it as an interpreter. Maybe the problem is that I use the wrong version of clang? I have tried updating all my macports packages such that none of them was outdated (there wasn't any outdate package to begin with). Reinstalled XCode, without any result.

**Comment by dariatols** [comment]
What's the best time for you for a meeting? I have a class scheduled in 5 minutes and a meeting with Niels at 14h.

**Comment by lelemmen** [comment]
@dariatols Is this issue fixed now?

**Comment by dariatols** [comment]
@lelemmen Semi, @guacke said I should run cmake from the terminal instead of VSCode so that's fixed now.
