### ISSUE TITLE
Kernels die in Jupyter Notebooks

### ISSUE THREAD

**Issue by dariatols** [GQCG/GQCP#590]
**Describe the bug**
After compiling the code on my device with CMake, I've imported `gqcpy` into a jupyter notebook. This import works fine, but the kernel always dies when I run the cell below [5] in `CCD.ipynb` and `CCSD.ipynb`. This issue occurs since I have rebased my branch `feature/CCD` using `develop`.
**Expected behavior**
The kernel should not die at this cell since it worked fine for me before the rebase.

**Screenshots and logs**
<img width="1434" alt="Screenshot 2020-06-21 at 13 05 10" src="https://user-images.githubusercontent.com/33431368/85263504-89884480-b46f-11ea-8503-f8a692d569ed.png">

**Operating system**
 - OS: macOS
 - Version 10.15.4

**Comment by lelemmen** [comment]
A possible fix could be to re-create the conda environment from this repository's `environment.yml` file and afterwards installing the Jupyter conda package into it:

``` bash
conda env create -f environment.yml
conda activate gqcp_dev
conda install -c conda-forge notebook 
```

Could you provide some feedback on this solution?

**Comment by dariatols** [comment]
This did not work for me. However, 
```
import os

os.environ['KMP_DUPLICATE_LIB_OK']='True'
```
did the trick but its warning concerns me: "As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results."

**Comment by lelemmen** [comment]
Thank you for your feedback. Since your problem has been resolved, I'm closing this issue.
