### ISSUE TITLE
INSTALL.md environment

### ISSUE THREAD

**Issue by dariatols** [GQCG/GQCP#592]
**Describe the bug**
I think there is a bug in the `INSTALL.md` file at 
```
conda activate gqcg_dev
```
I think this should be `gqcp_dev` instead of `gqcg_dev`. Otherwise it will just use the old `gqcg_dev` and this has no pybind11 installed I think.

**Comment by lelemmen** [comment]
The line you're mentioning is not present in the develop branch, so I'm closing this issue because there is no bug.
