### ISSUE TITLE
Installation on Graham and update on HPC-Ugent

### ISSUE THREAD

**Issue by nbilliet** [GQCG/GQCP#596]
As was discussed in the teams meeting on 30/06 with @guacke, the current version of GQCP on HPC-Ugent is outdated and not available on the Graham cluster.

- [x] Update HPC UGent installation
- [ ] Install GQCP on Graham

**Comment by guacke** [comment]
Update on HPC UGent done (see accompanying PR #546). Build of development branch can be found at gqcp/dev-intel-2019b-Python-3.7.4.

**Comment by guacke** [comment]
I have sent a mail to Compute Canada to enquire how users can install EasyBuild modules on Graham.

**Comment by lelemmen** [comment]
@guacke I've added a "waiting-for" label, indicating the current status of this issue.

**Comment by guacke** [comment]
We are currently switching to Docker. I am closing this issue as Singularity installs are currently working on the HPC UGent.
