### ISSUE TITLE
Fix Github Actions for MacOS builds

### ISSUE THREAD

**Issue by guacke** [GQCG/GQCP#597]
**Describe the bug**
Github Actions keeps failing on test 3, where the results of the Libint interface are compared with those generated from the Libcint interface. 

- [x] Ubuntu build
- [ ] Macos build
- [x] Ubuntu conda package
- [x] Macos conda package

**Comment by guacke** [comment]
@lelemmen I propose to temporarily disable the Github Actions test until I have resolved this issue, so that we no longer have failing tests (Travis CI does not have the same problem).

**Comment by lelemmen** [comment]
I agree, 100%.

**Comment by guacke** [comment]
This issue also effects the automatic publication of the GQCP conda package.

**Comment by guacke** [comment]
Test 3 is failing again. @dariatols Can you look at this?

**Comment by lelemmen** [comment]
Ahh, the pesky `IntegralCalculator` test. Are we convinced that libcint is at the root of this?

**Comment by guacke** [comment]
The current MacOS build hangs. This could be because we overflow the available memory by compiling in memory. If we fix this build, we can also offer the latest GQCP development version as a MacOS conda package.

**Comment by lelemmen** [comment]
Since we were able to merge #647, I guess the macOS builds don't hang anymore?

**Comment by guacke** [comment]
The MacOS Conda package deployment is functioning. I am not enabling the MacOS build by default as we are currently adjusting to a Docker-based workflow.
