### ISSUE TITLE
Travis fails (Python1.4)

### ISSUE THREAD

**Issue by lelemmen** [GQCG/GQCP#602]
**Describe the bug**
It seems that -out of nowhere-, Travis CI is failing again.

**Screenshots and logs**
One of the Travis CI logs is [here](https://travis-ci.com/github/GQCG/GQCP/builds/179222616), and here is the relevant part of the log:

> -- Found PythonInterp: /opt/pyenv/shims/python3.7 (found version "1.4") 
> 377CMake Error at /home/travis/miniconda/share/cmake/pybind11/FindPythonLibsNew.cmake:96 (message):
> 378  Python config failure:
> 379
> 380  pyenv: python3.7: command not found
> 381
> 382  
> 383
> 384  The `python3.7' command exists in these Python versions:
> 385
> 386    3.7
> 387    3.7.6

**Comment by lelemmen** [comment]
@guacke Do you happen to have time to resolve this devops-related issue?

**Comment by guacke** [comment]
@lelemmen I will address this issue in PR #603.
