### ISSUE TITLE
Enable Easybuild support on Compute Canada infrastructure: try Docker

### ISSUE THREAD

**Issue by guacke** [GQCG/GQCP#605]
CC uses a highly customized version of EasyBuild described in https://easybuilders.github.io/easybuild-tutorial/computecanada/. Although support is great, installing our own patched software seems troublesome (own changes are preferably converted to easybuild patches). Furthermore, there are issues with Eigen:

> I am currently working on a modified recipe for GQCP, and I am hitting what seems
> to be a bug in the FindEigen3.cmake file that you provide :
>
> CMake Error at cmake/FindEigen3.cmake:43 (file):
>   file failed to open for reading (No such file or directory):
>
>     /cvmfs/soft.computecanada.ca/easybuild/software/2020/Core/eigen/3.3.7//cvmfs/soft.computecanada.ca/easybuild/software/2020/Core/eigen/3.3.7/include/Eigen/src/Core/util/Macros.h
> Call Stack (most recent call first):
>   cmake/FindEigen3.cmake:92 (_eigen3_check_version)
>   CMakeLists.txt:23 (find_package)
>
>
> It tries to find a file named by its full path, inside of EBROOTEIGEN. The file is
> indeed there, but it prepends the full path with another full path.
>

**Comment by guacke** [comment]
I will investigate the use of Docker/Singularity as an alternative to the EasyBuild procedure, which seems ill-suited for the rapid devop cycles we require.

**Comment by lelemmen** [comment]
@guacke Is this issue still active? If it isn't, could you close it? If it is, could you propose next steps?
