### ISSUE TITLE
Create GitHub Actions for docusaurus site

### ISSUE THREAD

**Issue by dariatols** [GQCG/GQCP#609]
**Describe the feature you'd like**
An automatic build for the `gqcg.github.io` website using GitHub Actions.

**Comment by lelemmen** [comment]
Maybe we should make sure that the Github Actions are conditional:
- if the site files don't change, don't re-build and republish the site;
- only if .cpp files are changed, re-test the library.

**Comment by dariatols** [comment]
@lelemmen Travis CI does currently not support conditional builds. A workaround could be to include [`[skip ci]`](https://docs.travis-ci.com/user/customizing-the-build#skipping-a-build) to the commit message if we only change documentation for example.
