### ISSUE TITLE
Change Molecule __repr__() function to __str__()

### ISSUE THREAD

**Issue by dariatols** [GQCG/GQCP#610]
**Describe the current state of a part of the code**
In `gqcpy/Molecule/Molecule_bindings.cpp`, the representation of a `Molecule` object is now generated using `__repr__(const GQCP::Molecule& m)`. 

**Describe a change that would improve the code base**
In my opinion, it would be a good idea to change `__repr__` to `__str__()` such that printing the `Molecule` information becomes more intuitive. Using `__str__()`, we can now use the [`print()` function](https://www.journaldev.com/22460/python-str-repr-functions) to print a `Molecule`.

Second of all, a new function `description()`, analogous to other classes in `GQCP` could be implemented, both in the C++ library and the Python bindings. The `shift operator <<` and the new `__print__()` could use this `description()` function.

**Comment by xdvriend** [comment]
@dariatols What should the description function contain? The same as what is now printed (number of electrons, atoms & they coordinates)?

**Comment by dariatols** [comment]
@xdvriend Yes indeed!

**Comment by lelemmen** [comment]
Indeed!
