### ISSUE TITLE
Support for VScode setup

### ISSUE THREAD

**Issue by xdvriend** [GQCG/GQCP#611]
**Describe the feature you'd like**
I think it might be useful to add some sort of support, for example a guide, on how to set up VScode to contribute to GQCP. At the moment it can be very difficult to try and set up every .json file and the qgcp.code-workspace. By documenting this in either a "contributing" section on the new docusaurus site or the current installation.md files.

**Describe what the current code offers in relation to what it lacks**
A step by step guide on how to set up the VScode settings would be the most helpful for new members I believe. But feel free to tell me what you guys think on the subject.

**Comment by lelemmen** [comment]
I agree! I think this would fit in perfectly with the "developer docs" we're building.

I would even say that it would be better to move the contents from the current `.md`-files into the website itself.
