### ISSUE TITLE
GQCPy does not work on Python 3.8

### ISSUE THREAD

**Issue by xdvriend** [GQCG/GQCP#624]
**Describe the bug**
When trying to import gqcpy on a python 3.8 interpreter (e.g. Jupiter notebook), you get the following error:

`ImportError: Python version mismatch: module was compiled for Python 3.7, but the interpreter version is incompatible: 3.8.3 (default, Jul  2 2020, 11:26:31) `

**To Reproduce**
``` python
import sys
sys.path.insert(0, '/Users/xeno/documents/GQCP/build/gqcpy')

import gqcpy
```

**Additional context**
For a quick fix for Jupiter notebooks, you can always install a python 3.7 kernel manually (https://ipython.readthedocs.io/en/latest/install/kernel_install.html#kernels-for-python-2-and-3). This doesn't tackle the core issue however.

**Comment by lelemmen** [comment]
@GQCG/devops-developers I'm delegating this to you guys. Could you take a look at aligning the Python versions?
