### ISSUE TITLE
Complex GHF python bindings

### ISSUE THREAD

**Issue by xdvriend** [GQCG/GQCP#645]
**Describe the feature you'd like**
For GHF, using complex values is sometimes a necessity. It would be useful to include this feature in the python bindings.

**Describe what the current code offers in relation to what it lacks**
The current GHF python bindings only support real valued GHF.

**Comment by xdvriend** [comment]
@lelemmen In order to allow for complex variables in the HF methods, I will need to adjust the QCStructure class. Is it okay to refactor this using an additional template variable `<typename _Scalar>` or do you prefer another work-around?

**Comment by lelemmen** [comment]
Could you explain why `QCStructure<QCModel>` needs an additional template argument?

**Comment by xdvriend** [comment]
The GHF `optimize` method (and the other HF `optimize` methods) return a `QCStructure` containing the ground state parameters, like the electronic energy. `QCStructure` is defined using a `double` at the moment. Because of this, when adding the possibility to use `complex double` to the python bindings, you get an error because `QCStructure` cannot handle these `complex double`s. By adding the template parameter `_Scalar` to `QCStructure` It can handle `complex double`s as well. 

Like I said, I'm not sure this is the best way to solve this, but I do believe this is one way to circumvent this issue.

**Comment by lelemmen** [comment]
I see. While the energy should be theoretically real-valued (as the expectation value of a Hermitian operator), I think it's OK for us to support complex-valued energies as well. Here, holomorphic HF comes to mind.

You're free to add a scalar template argument to accommodate these changes.
