### ISSUE TITLE
Is gqcp_dev conda still required?

### ISSUE THREAD

**Issue by guacke** [GQCG/GQCP#646]
In light of the recent Docker support, is the `gqcp_dev` Conda environment still needed. The focus of Conda lies on providing software packages and not complete development environments. This has already lead to faulty dev environments, although the `gqcp_dev` Conda environment was correctly installed.

**Comment by guacke** [comment]
See also PR #642.

**Comment by lelemmen** [comment]
Based on your comment, I would say we can deprecate `gqcp_dev` as conda environment, using Docker's provisioning instead.
