### ISSUE TITLE
ONVPath API: C++ and python bindings

### ISSUE THREAD

**Issue by xdvriend** [GQCG/GQCP#661]
**Describe the feature you'd like**

- [x] A clean API for working with an ONV path would make the CI code a lot more readable. It would be good to refactor the existing code with the new API as well.

- [x] Adding python bindings would add a lot of freedom when running calculations.

- [ ] It would be cool to add a description that contains an ASCI image of the ONVPath as well.

**Describe what the current code offers in relation to what it lacks**
The current CI code is correct, but is not easy to understand. Creating a clean API for path manipulation would benefit the code a lot.

**Comment by lelemmen** [comment]
As discussed, @xdvriend and @dariatols, I'd like to you work on the following improvements:
- using the existing `ONVPath` in the one-electron operator evaluation code for `SpinUnresolvedONVBasis`;
- proposing a change on `ONVPath` (or proposing a new type altogether) which could be used in the two-electron operator evaluation code.

**Comment by lelemmen** [comment]
I'm splitting up this issue in its constituent parts.
