### ISSUE TITLE
Document the ONV manipulation extensively. 

### ISSUE THREAD

**Issue by xdvriend** [GQCG/GQCP#662]
**Describe the feature you'd like**
Documenting the ONV manipulation on the website would be great for developers.

**Describe what the current code offers in relation to what it lacks**
At the moment, the website does not contain this info.

**Comment by lelemmen** [comment]
This would make for a great first blog post (combining this documentation and #661).

**Comment by lelemmen** [comment]
This was implemented in the previous PR.
