### ISSUE TITLE
Spin-redistribution implementations

### ISSUE THREAD

**Issue by lelemmen** [GQCG/GQCP#663]
An epic for tracking progress on the implementation of the prerequisites for spin-redistribution implementations.

**Comment by xdvriend** [comment]
@ lelemmen Is it possible we need the ability to calculate spin density matrices to be able to perform spin constrained CI calculations?

**Comment by xdvriend** [comment]
Issue #680 ties into this issue, as it is needed to further the implementation of these API's.
