### ISSUE TITLE
ONVManipulator `N` member public instead of protected?

### ISSUE THREAD

**Issue by dariatols** [GQCG/GQCP#668]
I'm writing the 'new' version of `shiftUntilNextUnoccupiedOrbital` in `ONVPath`. Since this class does not inherit from any classes, I can't access the member variables of `onv_basis` (`onv_basis` is a `SpinUnresolvedONVBasis` type member variable of `ONVPath`). Do I have your permission to change the `N` variable of `ONVManipulator` to public instead of protected @lelemmen?

**Comment by lelemmen** [comment]
`ONVManipulator` provides a public method `numberOfElectrons()`. Instead of changing the public/private interface, why not use this API instead?

**Comment by dariatols** [comment]
I've looked over this function. Thanks!
