### ISSUE TITLE
Add central versioning

### ISSUE THREAD

**Issue by guacke** [GQCG/GQCP#673]
**Describe the feature you'd like**
All Conda and Docker releases need to be version tagged (i.e. 0.0.1, dev, ...). 

**Describe what the current code offers in relation to what it lacks**
Currently both the develop branch and the release branches overwrite the same images.

**Comment by lelemmen** [comment]
I'll merge the current `develop` branch, i.e. at commit [4ebb780](https://github.com/GQCG/GQCP/commit/4ebb780376330011bec2d7393611aad68a0188ae) into master, tagging it with `v0.0.1`.

**Comment by lelemmen** [comment]
@guacke I've just created a `v0.0.1` release on GitHub!
