### ISSUE TITLE
Conda does not find libint=2.4.2 anymore.

### ISSUE THREAD

**Issue by dariatols** [GQCG/GQCP#676]
**Describe the bug**
Conda cannot find the `libint` package with version 2.4.2. However,  when 
```
conda search -c conda-forge libint
```
is executed, it will find only version 2.6.0. Changing this in [`environment.yml`](https://github.com/GQCG/GQCP/blob/develop/environment.yml) resolved this issue for me.

**To Reproduce**
```
conda env create -f environment.yml
```

**Expected behavior**
I expected conda to download all packages.

**Screenshots and logs**
```
(base) dariatolstykh@Darias-MBP GQCP % conda env create -f environment.yml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - libint=2.4.2
```

**Operating system**
 - OS: macOS
 - Version 10.15.6

**Comment by dariatols** [comment]
However, if I use the latest version of `libint`, the build of GQCP will not pass anymore.

**Comment by lelemmen** [comment]
@dariatols What's the current status of this bug. Does using Docker as provisioning help?

**Comment by xdvriend** [comment]
@lelemmen, I believe @guacke disabled this on purpose in order to push a docker oriented way of working.

**Comment by lelemmen** [comment]
@guacke I remembered something like this, indeed. Since we have [user documentation](https://gqcg.github.io/GQCP/docs/user_documentation/user_getting_started) and [developer documentation](https://gqcg.github.io/GQCP/docs/developer_documentation/developer_getting_started) on getting started, can we remove the `environment.yml` file?

**Comment by dariatols** [comment]
Indeed, this issue is resolved using Docker containers.

**Comment by lelemmen** [comment]
Then I'll close this issue, since it was related to GQCP-developers provisioning.
