### ISSUE TITLE
Remove code duplication in const reference vs. reference 'getters'

### ISSUE THREAD

**Issue by lelemmen** [GQCG/GQCP#690]
**Describe the current state of a part of the code**
In many types, we're exposing a read-only (`const &`) and a writable (`&`) reference to a type's underlying member.

**Describe a change that would improve the code base**
Currently, we're duplicating the related source code. However, [this post](https://stackoverflow.com/a/856839) describes a solution to this code duplication, using `const_cast`. Since we'd be implementing the `&` method using the `const &`, there is absolutely no problem in using the (sometimes dangerous) `const_cast`.

**Additional context**
@dariatols @xdvriend I've assigned you both, but feel free to delegate between yourselves. I think this is a rewarding refactor, plus you'll get more fluent in understanding C++'s sometimes obscure syntax. See, for example, the `StorageArray` class:

```c++
return const_cast<Element&>(const_cast<const Self*>(this)->operator()(indices...))
```

**Comment by xdvriend** [comment]
@dariatols is it okay that I tackle this issue?

**Comment by dariatols** [comment]
> @dariatols is it okay that I tackle this issue? 

Sure! I'll jump into these issues on Wednesday!

**Comment by xdvriend** [comment]
@lelemmen, is this refactor necessary on, for example:

```C++
/**
 *  @return A vector of read-only matrix representions of the parameters/integrals of this operator.
 */
const std::vector<MatrixRepresentation>& allParameters() const { return this->array.elements(); }

/**
 *  @return A vector of writable matrix representions of the parameters/integrals of this operator.
 */
std::vector<MatrixRepresentation>& allParameters() { return this->array.elements(); }
``` 
for consistency? Or can I leave trivial methods like this as they are?

**Comment by lelemmen** [comment]
> Or can I leave trivial methods like this as they are?

You sure can. The code would be less readable with the `const_cast`s!
