### ISSUE TITLE
Use struct for traits

### ISSUE THREAD

**Issue by dariatols** [GQCG/GQCP#706]
**Describe the current state of a part of the code and a change that would improve the code base**
In the current code, a trait is alternatively defined as a `struct` or `class`. In my opinion, it would be better to implement them all as `struct`s as their members should be stored as `public`.

**Comment by dariatols** [comment]
I'll tackle this issue to get more acquainted with traits and CRTP @lelemmen.

**Comment by lelemmen** [comment]
@dariatols If you want, you can change the ZenHub estimate. The '1' was with me as an assignee in mind.

**Comment by dariatols** [comment]
@lelemmen I've changed this to 3 now.
