### ISSUE TITLE
Scrutinize R/U/GHF and improve its APIs

### ISSUE THREAD

**Issue by lelemmen** [GQCG/GQCP#710]
**Describe the current state of a part of the code**
In #688, we've done a lot of compile-time corrections to the code. One of the byproducts of this is that possibly the APIs that are used in the R/U/GHF modules (both in `QCMethod` as in `QCModel`) don't use the most up-to-date R/U/G types.

**Describe a change that would improve the code base**
It would be good if the HF modules would be scrutinized and checked if their APIs need to be updated to reflect the most up-to-date types we have.

**Additional context**
@xdvriend Could you take the lead for this? Of course, this would only be possible after #707 is closed.

**Comment by xdvriend** [comment]
Yes, with pleasure! I'll keep an eye on your PR so I can start on this when you're done. I'll assign myself to this issue as well.

**Comment by xdvriend** [comment]
Possible changes to the code:

- [ ] The UHF `QCModel` is written with 2 `transformationMatrices` for C, this can be done with a `UTransformationMatrix`.

The R/GHF methods and `QCModel` look good to me. I'll start with reworking UHF before double checking the other two methods.
