### ISSUE TITLE
Use einsum-like API for contractions

### ISSUE THREAD

**Issue by lelemmen** [GQCG/GQCP#711]
**Describe the current state of a part of the code**
In #707, I've added an initial implementation for a `np.einsum`-like API for contracting tensors. I'm not sure it works, yet, though.

**Describe a change that would improve the code base**
- [x] Finish the implementation for `Tensor.einsum`;
- [x] Add a subsequent `Tensor.einsum`-API, that fully uses the `"left, right->output"` arguments. Split the input string and forward the argument to the previous `einsum`. This way, we come as close as possible to a C++ `einsum` API;
- [x] Test the implementation for `Tensor.einsum`;
- [x] Scrutinize the current code base for tensor contractions, and replace them all with the `einsum`-API;
- [x] Deprecate the API `Tensor.contractWithMatrix` and replace it with equivalent `einsum` calls.

**Additional context**
@dariatols @xdvriend Who can I delegate this issue to?

**Comment by xdvriend** [comment]
As discussed today, I'll tackle this issue as it covers some necessary implementations for the stability analysis implementation I'm starting on next week.

**Comment by xdvriend** [comment]
@lelemmen, am I correct when I say that the first two points of this issue have already been resolved? Or do I have to adjust something on the implementation you provided?

**Comment by lelemmen** [comment]
- The first point might indeed be done. I'm not sure if what I've implemented is fully correct, so we still need to test it. I might have specified wrong ranges, used something wrong, etc. I don't know, I just didn't have the time in a previous PR to check it perfectly.
- The second point is a new API to be implemented. I've now given the API as `einsum(other, left_indices, right_indices, output_indices)`, but I'd really like to support the one-string API like NumPy's einsum, i.e. with the comma and the right arrow.

**Comment by xdvriend** [comment]
Allright, got it! I'll start by writing some tests and I'll go from there then. I was also thinking, is it worth trying to write the einsum API for matrices as well? This would, in the end, allow us to use things like `einsum('ij, ijkl -> kl', matrix, tensor)`. Or do you believe that this would just be quite a lot of work for nothing?

**Comment by lelemmen** [comment]
While I think that could be useful, let's not focus on that right now.

**Comment by xdvriend** [comment]
@lelemmen, whenever I try to use the einsum API, I get some errors while building. (I'm not sure whether I'm doing something wrong or whether the errors originate somewhere else.)

I believe it goes wrong with line 292: ` Tensor<Scalar, ResultRank> T_intermediate = this->contract(rhs, contraction_pairs);`

![Screenshot 2020-11-03 at 17 54 09](https://user-images.githubusercontent.com/54795591/98016175-f2a89d00-1dfd-11eb-9444-e042203e4717.png)
![Screenshot 2020-11-03 at 17 54 25](https://user-images.githubusercontent.com/54795591/98016179-f4726080-1dfd-11eb-875d-6fe2b1a8e21b.png)

**Comment by lelemmen** [comment]
Ah, yes, indeed. You're going to have to call `this->Eigen().contract(...)`. The reason for this is that some traits aren't carried over from `Eigen::Tensor` to `GQCP::Tensor`, and by calling `.Eigen()` you're converting from `GQCP::` to `Eigen::`.

**Comment by xdvriend** [comment]
I had to call 
`this->contract(rhs.Eigen(), contraction_pairs)`
but the issue was indeed the convergence from `GQCP::Tensor` to `Eigen::`!

**Comment by xdvriend** [comment]
@lelemmen, somewhere within this for loop the index of the string goes "out of bounds". I believe it is because the if-statement never gets called. I'm looking into why this is.
![Screenshot 2020-11-04 at 12 04 09](https://user-images.githubusercontent.com/54795591/98103963-17e8ea00-1e96-11eb-8422-3101b6f2ca01.png)
