### ISSUE TITLE
CISolver DOCI Davidson long test durations

### ISSUE THREAD

**Issue by tmhuysen** [GQCG/gqcp#76]
The very high test durations of the Davidson timings could be indicative of an underlying issue.

**Comment by lelemmen** [comment]
Maybe the issue is related to just using debug flags and not -O3, or boost's unit test module

**Comment by tmhuysen** [comment]
We're using copy getters for our Operator wrapper classes in the HamiltonianParameters.
`GQCP::OneElectronOperator get_S() const { return this->S; }`
should be
`const GQCP::OneElectronOperator& get_S() const { return this->S; }`
My local tests timings dropped from 90 seconds to 0.12.

**Comment by lelemmen** [comment]
This was implemented in #101.
