### ISSUE TITLE
Python bindings can no longer quantize operators

### ISSUE THREAD

**Issue by xdvriend** [GQCG/GQCP#784]
**Describe the bug**
The new compile-time correct operators don't have any python bindings yet. This causes a type error while trying to run several calculations, like Hartree-Fock.

**To Reproduce**
<img width="981" alt="Screenshot 2020-11-12 at 10 42 16" src="https://user-images.githubusercontent.com/54795591/98923377-dbd80980-24d3-11eb-9e16-b05e1d0a702e.png">

**Expected behavior**
Quantizing the operator returns a new type (`RSQOneElectronOperator` in this case). B ut this new type is not yet recognised by python.

**Comment by lelemmen** [comment]
After #762, this will be fixed.
