### ISSUE TITLE
Conda builds are failing

### ISSUE THREAD

**Issue by lelemmen** [GQCG/GQCP#800]
**Describe the bug**
Our GitHub Actions are failing due to conda.

**Screenshots and logs**

![Schermafbeelding 2020-11-20 om 13 58 15](https://user-images.githubusercontent.com/23526798/99802755-8a192a00-2b38-11eb-8f29-260e0c1cc345.png)

**Additional context**
See the [GitHub Action](https://github.com/GQCG/GQCP/actions/runs/374309831).

@GQCG/devops-developers

**Comment by guacke** [comment]
I am working on this issue in PR #804. However, develop appears to be contaminated:

```
  Cannot find source file:

    /__w/GQCP/GQCP/gqcp/include/QCModel/HF/StabilityMatrices/RHFStabilitymatrices.hpp
```

@xdvriend Could you provide a bugfix for develop?

**Comment by xdvriend** [comment]
@guacke It should be done (see PR #805 ). I didn't have any errors locally so that's probably why the mistake stayed in the code.
