### ISSUE TITLE
Determine the scope and sections of the documentation

### ISSUE THREAD

**Issue by lelemmen** [GQCG/GQCP#809]
Intuitively, I think there should be 3 parts in the documentation, according to the developer stack:
- Users
- Method developers
- GQCP developers / DSL designers

But what kind of documentation is required for each of the three categories?

**Comment by dariatols** [comment]
What would be the difference between a method and a GQCP developer?

**Comment by lelemmen** [comment]
A method developer is someone who uses GQCP's building blocks in order to implement a new computational method. (Like we have done in the QCMethod/ folder). A DSL designer is someone who creates and designs and refactors GQCP's building blocks, like spinor bases, transformations, etc.

**Comment by lelemmen** [comment]
After thinking this through, I'd say the scope of the documentation is only twofold:
- Use cases for new GQCP users (either 'computational experimentalists' or 'method developers'). I'd say these should all be geared towards new GQCP users, providing Jupyter Notebooks / live executable cells with the examples.
- A developer's documentation on how GQCP's building blocks can be used and why they are available.
