### ISSUE TITLE
Simple2DM_test failing in Conda linux builds.

### ISSUE THREAD

**Issue by guacke** [GQCG/GQCP#833]
**Describe the bug**
Conda builds on Linux have one test failing
```
17/85 Test #17: Simple2DM_test .................................***Failed    0.06 sec
Running 3 test cases...
Will read basis set from $PREFIX/share/libint/2.4.2/basis/sto-3g.g94
$SRC_DIR/gqcp/tests/DensityMatrix/Simple2DM_test.cpp(137): error: in "two_electron_operator_expectation_value_different_orbital_bases": check std::abs(exp_val_AO - exp_val_random) < 1.0e-12 has failed

*** 1 failure is detected in the test module "Simple2DM"
```

**To Reproduce**
Consult CI for commit c1f88dc in PR #831.

**Comment by guacke** [comment]
Now also failing on Docker builds (see develop). @lelemmen @xdvriend Could you take a look?

**Comment by xdvriend** [comment]
Locally, the test runs fine without any errors. Since the error occurs in the check with the random-basis expectation value, is it possible that the random generator is not seeded & gave some sort of one-off result where the test failed?
