### ISSUE TITLE
Change overlap argument in HF modules

### ISSUE THREAD

**Issue by lelemmen** [GQCG/GQCP#845]
There are still some minor inconsistencies between the HF modules.

A large part of them are written using the correct one-electron operators, but the 'overlap matrix' is required as an argument for the environments.

It would be better if we changed this to `R/U/GSQOneElectronOperator` instead of `SquareMatrix`.

**Comment by xdvriend** [comment]
I'll adjust this in my current PR. It shouldn't be too much work and I'm already tackling some HF refactors there anyway.
