### ISSUE TITLE
Use spin as argument for SpinResolved DysonOrbital

### ISSUE THREAD

**Issue by dariatols** [GQCG/GQCP#870]
In the theoretical section (see https://github.com/GQCG-res/dariatols_knowdes/issues/15), we define a Dyson amplitude as `<N-1, (I) | â_P | N, (J)>` with spinor index `P` for a spinor basis and `<N-1, (I) | â_p\sigma | N, (J)>` with spin-orbital index `p\sigma` for a spin-orbital basis. In this way, it is important to specify in which spin compound our spin-orbital has when we are ejecting an electron out of it. 

I think this can be done in `GQCP` using `Spin` as an argument for `DysonOrbital::TransitionAmplitudes` in the `SpinResolved` case. For the `SpinUnresolved` case, spin does not matter.

**Comment by lelemmen** [comment]
@dariatols I haven't really thought this through, but I'd be happy to review your small refactor proposal in a PR.

**Comment by dariatols** [comment]
I'm still not sure how to tackle this problem in the most efficient way. First, I will rewrite the theoretical section and this will probably lead to an idea on how to incorporate the Dyson spin-orbital in GQCP.

**Comment by dariatols** [comment]
After considering the pros and cons of separating the `DysonOrbital` class for the `SpinUnresolved` (spinor) and `SpinResolved` (spin-orbital) case, I think it is better to keep the constructor for both bases in a general class `DysonOrbital`. 

Secondly, providing `Spin` as an argument for the named constructor for the `SpinResolved` case will not necessarily result in an easier-to-read code. It will, in my opinion, only create an extra burden for the user to provide which spin the ejected electron has while this can be done behind the scenes in GQCP.
