### ISSUE TITLE
Overlap zero initialization.

### ISSUE THREAD

**Issue by tmhuysen** [GQCG/gqcp#89]
For the FCIDUMPReader we find:
https://github.com/GQCG/gqcp/blob/8cdabb04f8d698a773f21b51649ce4830a3e22be/src/HamiltonianParameters/HamiltonianParameters_constructors.cpp#L201

This should be `Eigen::Matrix::Identity(K, K)` not `Eigen::Matrix::Zero(K, K)`

**Comment by lelemmen** [comment]
This has been fixed.
