### ISSUE TITLE
Problems with building GQCP

### ISSUE THREAD

**Issue by xdvriend** [GQCG/GQCP#934]
**Describe the bug**
When I try to build GQCP, either locally or within a docker container, I'm encountering some issues. 

*Locally*
After updating boost and Libint (to 1.73 and 2.6.0 respectively) I got warnings concerning the following implementation:

`bool areIntegralsAllZero() const { return false; }`
(However I thought these could be solved by marking the function with `override`, so I tried that. The build now continued without warnings.)

Subsequently, the build halts at the following point:
![Screenshot 2021-04-06 at 11 31 25](https://user-images.githubusercontent.com/54795591/113690414-a83c8c80-96cb-11eb-9e17-7b0d70065d68.png)

*Docker*
After pulling the latest docker container and setting the cmake options as shown in the documentation on the GQCP website, I get the following error when trying to build GQCP:
![Screenshot 2021-04-06 at 11 33 21](https://user-images.githubusercontent.com/54795591/113690624-e934a100-96cb-11eb-8019-ec3db51c801a.png)

**Operating system**
 - OS: Big Sur
 - Version 11.2.3

**Comment by guacke** [comment]
@xdvriend Please provide the entire Docker build log.

**Comment by xdvriend** [comment]
Once I use the command 

`make -j 8 && make test && make install`

I immediately get that error.

**Comment by guacke** [comment]
@xdvriend Also provide the output from the respective CMake commands. Note that /opt/local/bin/cmake can never be found, as this points to a local Mac installation. Removing your build directory and rebuilding could already help.

**Comment by xdvriend** [comment]
> @xdvriend Also provide the output from the respective CMake commands. Note that /opt/local/bin/cmake can never be found, as this points to a local Mac installation. Removing your build directory and rebuilding could already help.

![Screenshot 2021-04-06 at 11 55 08](https://user-images.githubusercontent.com/54795591/113693511-f7d08780-96ce-11eb-97fc-e56bad3a8dd9.png)

This is the output from the CMake option commands

**Comment by guacke** [comment]
@xdvriend The commands passed to CMake to not correspond to those that are documented in the `build-and-test.yml` workflow. I have provided a Docker centric VSCode configuration in PR #935. I will appoint you as reviewer of that branch so that you can check that the configuration therein is sufficient to compile GQCP with the pre-installed and pre-configured CMake VSCode extensions.
