### ISSUE TITLE
.tensor() python bindings not working

### ISSUE THREAD

**Issue by xdvriend** [GQCG/GQCP#940]
**Describe the bug**
Even though `<pybind11/eigen.h>` is imported, the `.tensor()` call of an Eigen::Tensor (`Pure/MixedspinResolvedComponent` for example, gives an error saying the type cannot be converted to a python type.)

**To Reproduce**

![Screenshot 2021-04-12 at 12 04 23](https://user-images.githubusercontent.com/54795591/114377705-3fe82200-9b87-11eb-8e31-4f98d0061926.png)

**Expected behavior**
I would expect, since the correct pybind module is imported, python would be able to handle a tensor as it does with a matrix, something goes wrong however.

**Operating system**
 - OS: MacOS
 - Version Big Sur 11.2.3
 - gqcg/gqcp - latest is the docker container in which I'm trying to run the calculation.

**Comment by lelemmen** [comment]
Pybind does not enable an automatic conversion from `Eigen::Tensor` to `np.ndarray`.

If you want to access the raw matrix representation of a tensor-like object, I think it would be best to use the `gqcpy` stand-alone method `asNumpyArray` in the Python bindings. I guess we forgot this so this is an oversight.

**Comment by xdvriend** [comment]
> Pybind does not enable an automatic conversion from `Eigen::Tensor` to `np.ndarray`.
> 
> If you want to access the raw matrix representation of a tensor-like object, I think it would be best to use the `gqcpy` stand-alone method `asNumpyArray` in the Python bindings. I guess we forgot this so this is an oversight.

Allright, I'll adjust it in the bindings and create a PR when I get it working.
