### ISSUE TITLE
`np.eigh` hangs in Docker

### ISSUE THREAD

**Issue by lelemmen** [GQCG/GQCP#958]
**Describe the bug**
When trying to diagonalize a complex matrix using `np.eigh` in the GQCP Docker container, the kernel hangs.

**Operating system**
 - OS: macOS 11.2.3
 - Docker: Most recent container from https://hub.docker.com/r/gqcg/gqcp

**Additional context**
This seems like a severe bug. @guacke

**Comment by dariatols** [comment]
Not only `eigh` hangs, NumPy matrix multiplications using `@` or `np.matmul()` are not executed within our Docker. I'll try to fix this ASAP (when the thesis students have handed in their research plan).

**Comment by lelemmen** [comment]
Yes, this seems to resolve the issue.

By the way, it's even possible to do this from within a Jupyter Notebook:
```shell
!python -m pip uninstall numpy --yes
!python -m pip install numpy --yes
```

**Comment by guacke** [comment]
@dariatols and @lelemmen I can execute the following code in the latest GQCP container:

```python
dim = 10
X, Y = np.random.rand(dim, dim), np.random.rand(dim, dim)
X @ Y
Z = np.matrix(np.random.rand(10, 10) + np.random.rand(10, 10) * 1j)
H = 1./2. * (Z + Z.H)
np.linalg.eigh(H)
```

Are you running the latest containers (see e.g. https://www.whitesourcesoftware.com/free-developer-tools/blog/update-docker-images/)? @dariatols Could you provide a test that currently fails on your local infrastructure? @lelemmen Do these kernel crashes also occur in the Singularity containers?

**Comment by lelemmen** [comment]
It seems that this bug has been resolved with the newest Docker containers, both locally and through Singularity.
