### ISSUE TITLE
NOCI implementation

### ISSUE THREAD

**Issue by xdvriend** [GQCG/GQCP#995]
In order to continue John's research and my own, it would be good to add the possibility to perform NOCI calculations to GQCP. As this would entail several new classes to be implemented, this issue has the form of an epic and the constituent parts will be added in separate issues.

**Comment by lelemmen** [comment]
For inspiration, feel free to take a look at the `prototypes` folder in my `spin-transitions` research repository. It contains a couple of classes that I've found useful while generating NOCI results.

**Comment by xdvriend** [comment]
> For inspiration, feel free to take a look at the `prototypes` folder in my `spin-transitions` research repository. It contains a couple of classes that I've found useful while generating NOCI results.

Thanks! I will most certainly do that. 😄
